name: 'drive-inc-challenge'

version: '3'
services:
  # node
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mynetwork

  # React
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules # fixes bug "Error: Cannot find module @rollup/rollup-win32-x64-msvc. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828)"
    networks:
      - mynetwork
    depends_on:
      - server

volumes:
  node_modules: {}

networks:
  mynetwork:
    driver: bridge
